name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Gain More Rights
      run: chmod +x "${GITHUB_WORKSPACE}/.github/script.sh"
    - name: Run Bash Script
      run: "${GITHUB_WORKSPACE}/.github/script.sh"
